# Generated by Django 3.2.7 on 2021-10-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('icon', models.CharField(max_length=256)),
                ('source', models.CharField(max_length=256)),
                ('size', models.CharField(max_length=256)),
                ('tag', models.TextField()),
                ('loaddate', models.CharField(max_length=256)),
                ('fields', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('data', models.TextField()),
                ('user_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=128)),
                ('type_element', models.CharField(choices=[('J', 'join'), ('O', 'operation'), ('F', 'filter'), ('T', 'output')], max_length=1)),
                ('many', models.BooleanField()),
                ('inputs', models.TextField()),
                ('outputs', models.TextField()),
            ],
        ),
    ]
